name: CI

on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_ROOT_PASSWORD: ""
        ports:
          - "3306:3306"
        options: --health-cmd="mysql -e 'SELECT 1' >/dev/null" --health-interval=10s --health-timeout=10s --health-retries=10

    steps:

      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup test database
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: ""
          MYSQL_HOST: 127.0.0.1
        run: bin/rails db:setup

      - name: Run tests
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: ""
          MYSQL_HOST: 127.0.0.1
        run: bin/bundle exec rspec
